name: Liveliness Check
on: 
  pull_request:
  push:
    branches: main
  schedule: 
    - cron: "0 8 * * *" # 3:00am UTC-5

jobs:
  check-liveliness:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Bring up Berachain
        run: |
          make startd
      - name: check
        run: |
          ./check_liveliness.sh 10 10 10 http://localhost
        working-directory: .github/workflows